version: '3.8'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    volumes:
      - ./volumes/database/postgres-dev:/var/lib/postgresql
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_DB: "shapeupdev"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    networks:
      - shapeup-network
    restart: always

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_USERNAME:dev
      - MONGO_INITDB_PASSWORD:dev
      - MONGO_INITDB_DATABASE:shapeupdev
      - TZ:America/Sao_Paulo
    ports:
      - "27017:27017"
    networks:
      - shapeup-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - shapeup-network

#  shapeupbackendapp:
#    build:
#      dockerfile: ./Dockerfile
#      context: .
#    container_name: shapeup-backend-app
#    environment:
#      - SPRING_PROFILES_ACTIVE=local
#      - MONGO_PORT=27017
#      - MONGO_HOST=mongodb
#      - MONGO_DATABASE=shapeupdev
#    depends_on:
#      - postgres-db
#      - mongodb
#      - redis
#    ports:
#      - "7000:7000"
#    networks:
#      - shapeup-network

networks:
  shapeup-network:
    external: true