server:
  port: 7000

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import:
      - optional:file:./variables-local.properties
    activate:
      on-profile: local
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /shapeup/swagger-ui
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: loggers

logging:
  level:
    root: info