version: '3.8'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    volumes:
      - ./volumes/database/postgres-dev:/var/lib/postgresql
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_DB: "shapeupdev"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    networks:
      - pg-db-network
      - mongo-network
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "dev"
      TZ: "America/Sao_Paulo"
    ports:
      - "6543:80"
    depends_on:
      - postgres-db
    networks:
      - pg-db-network
    restart: always

  mongo-db:
    container_name: mongo-db
    image: mongo
    restart: always
    volumes:
      - ./volumes/database/mongo-dev:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_USERNAME: dev
      MONGO_INITDB_PASSWORD: dev
      MONGO_INITDB_DATABASE: shapeupdev
      TZ: "America/Sao_Paulo"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_USERNAME: dev
      MONGO_INITDB_PASSWORD: dev
      MONGO_INITDB_DATABASE: shapeupdev
    networks:
      - mongo-network

networks:
  pg-db-network: {}
  mongo-network: {}