version: '3.8'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    tty: true
    volumes:
      - ./volumes/database/postgres-dev:/var/lib/postgresql
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_DB: "shapeupdev"
      SPRING_PROFILES_ACTIVE: qa
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    networks:
      - pg-db-network
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "dev"
      TZ: "America/Sao_Paulo"
    ports:
      - "6543:80"
    depends_on:
      - postgres-db
    networks:
      - pg-db-network
    restart: always

  shape-up-api:
    container_name: shape-up-api
    image: shapeup/shapeup-api:latest
    environment:
      TZ: "America/Sao_Paulo"
    depends_on:
      - postgres-db
    ports:
      - "7000:7000"
    networks:
      - pg-db-network
    restart: always

networks:
  pg-db-network: {}