version: '3.9'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    tty: true
    volumes:
      - ./volumes/database/postgres-dev:/var/lib/postgresql
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_DB: "shapeupdev"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    networks:
      - pg-db-network
      - general-network
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "dev"
      TZ: "America/Sao_Paulo"
    ports:
      - "6543:80"
    depends_on:
      - postgres-db
    networks:
      - pg-db-network
      - general-network
    restart: always

  mongo-db:
    container_name: mongo-db
    image: mongo
    restart: always
    volumes:
      - ./volumes/database/mongo-dev:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_DATABASE: shapeupdev
      TZ: "America/Sao_Paulo"
    ports:
      - "27017:27017"
    networks:
      - mongo-network
      - general-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - redis-network
      - general-network

  shape-up-api:
    container_name: shape-up-api
    image: shapeup/shapeup-api:43
    env_file:
      - .env
    environment:
      TZ: "America/Sao_Paulo"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_BUCKET_NAME}
    depends_on:
      - postgres-db
      - mongo-db
      - redis
    ports:
      - "7000:7000"
    networks:
      - pg-db-network
      - mongo-network
      - redis-network
      - general-network
    restart: always

networks:
  pg-db-network: { }
  mongo-network: { }
  redis-network: { }
  general-network: { }